name: artemis
channels:
- conda-forge
dependencies:
- python >3.9,<3.13
- pip
- scikit-learn
- pymol-open-source
- pip:
  - pytest
  - -e .
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - tqdm
