name: CI & CD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      uses: mamba-org/setup-micromamba@v1
    - name: Precommit Checks
      uses: pre-commit/action@v3.0.1
    - name: Run tests
      run: pytest -v --noconftest --numprocesses=4 --cov=tqchem --cov-report=xml --no-cov-on-fail --cov-branch tests
      shell: micromamba-shell {0}
